# Generated by Django 4.2.3 on 2023-08-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriptiton',
            new_name='description',
        ),
    ]
